language: node_js
dist: jammy
node_js:
- 22.5.1
cache:
  directories:
  - node_modules
  - build
script:
- echo "hello world"
- npm install
deploy:
  provider: heroku
  app: ds26gte-boardg
  on:
    all-branches: true
  skip_cleanup: true
  api_key:
    secure: "C1MRr7TbvPmHJieQFyMxLDZbApAaJ9u+nKpGjsVr3AaA8j9Z4RE7x5vIltiEXJmAbOnOgJ/RrW15fOiwocenZKPwt9/W4M3N7zWIKygp1tpvb4UE0iN+OJxgCWv3iVowWssz9Th/6zEoinyRo7aGK7oLD9kU97W9zMCAxZSW30MHxqzbVz28zyV4UHtbOmrU4Fa3nw9Yn1RWFBHR4yqnE0fY/tX+4llQUg8GxnYvmlXp8g1INo3vgUxAEc/b7fCRUpU0hUCBRYfleFl+m58GjlEAzdLqNfz6dHVYIIRSozM/DCIfP5WFBfMoq17lkzy9MH0djadDJ7FfMu0vGwaBR3yUs16lva+wqyhKlCXsVVtU+9PwOzSRE4DgkxQTo6cTTkVa2DXnsJT/o+HvlIhHWZ6/nRiXh5if+VBDCm4E52T/VVbTqtv8QjX02pMST6caxyTcI+6tLlqxo+8gTLNynn28KjlZCnkUjjc8HFCF84HdoTT55XPq2BMNAn+EsX+p5ZWOtfdaxBZFTLr6C59OumY0WdrSIc7aL+tTp09P4D8KcvlX2jXDeWT41FJOgN1ymoZ2r3w1KZnBlrKuO/8w1vmVQPMYXgUeilqnzLGEY2TrSRBxn7CNYd5+Wylt2Vyz1fX3IbKLO9nEWg167+MAh3R7aHo12iBRFJF79hpF6CI="
